services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - php

  php:
    image: ghcr.io/namer203/php-app:latest
    volumes:
      - ./app:/var/www/html
    environment:
      DATABASE_URL: mysql://app:app@db:3306/app
      REDIS_HOST: redis

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: igra_app
      MYSQL_USER: igra_user
      MYSQL_PASSWORD: geslo
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./app/db_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email likar.vavken.tjas@gmail.com -d devopsdocker.top --agree-tos

volumes:
  db_data:
  redis_data:
  certbot_conf:
  certbot_www:
